### PR TITLE
fix: workflow now cancels itself when newer workflow is detected

### LINKED ISSUE #21: old workflow cancels newer one
Hey @rokroskar,

I just had the following situation:
I merged 3 PRs in quick succession. Because of this 3 workflows were created on the master branch of that repository. Because all 3 workflows were `queued` or `in progress` the first workflow cancelled the other two. Unfortunately the first workflow was not the latest. 
I'll make an example for clarification: 
I merged PR `A`, `B` and `C`. `A` ist the first PR I merged, `C` the last. 
Expected behaviour: Workflow `C` is the only one running.
Actual behaviour: Workflow `A` cancelled workflow `B` and `C` and was the only one running. 

Afterwards I inspected the workflows and realized that the `workflow_run_id` is an incrementing number. If we assume that statement we could add a little logic, so that workflows with a higher id will not be cancelled. And if any workflow with a higher id is detected the current workflow cancels itself too.

What do you think about this idea?

### PR DESCRIPTION
**Pull request by mustaphazorgati**
Hey @rokroskar,

here's the improvement regarding issue #21.

I decided to replace the hacky grep with a jq call.
This PR assumes that the run ids are incremental. I didn't confirm this from any documentation. Was just an observation. Maybe we should verify that assumtion?

closes #21

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -35,7 +35,15 @@ function convertToKeyValuePairs() {
 }
 
 function getRunningWorkflowIds() {
-  jq ".workflow_runs | .[] | select(.head_branch==\"${branch}\" and .head_repository.full_name==\"${repo}\" and .status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\") | .id " | grep -v "${GITHUB_RUN_ID}" || :
+  local workflow_ids=$(jq ".workflow_runs | .[] | select(.head_branch==\"${branch}\" and .head_repository.full_name==\"${repo}\" and .status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\") | .id ")
+  local condition="<"
```
Comment (mustaphazorgati) [inline entrypoint.sh:40]: This ensures that every id returned is smaller than `GITHUB_RUN_ID`. No newer workflows will be cancelled.

File: entrypoint.sh [hunk 2]
```diff
@@ -35,7 +35,15 @@ function convertToKeyValuePairs() {
...
+  for id in $workflow_ids; do
+    if [[ "$id" -gt "$GITHUB_RUN_ID" ]]; then
+      condition="<="
```
Comment (mustaphazorgati) [inline entrypoint.sh:43]: If any newer workflow is detected this condition will cause this function to return `GITHUB_RUN_ID` too. Which results in cancellation of the current workflow (because a newer is present anyway)

**Comment by mustaphazorgati** [comment]
regarding the assumption: All I could finde is "A unique number for each run within a repository. This number does not change if you re-run the workflow run."

File: entrypoint.sh [hunk 3]
```diff
@@ -35,7 +35,15 @@ function convertToKeyValuePairs() {
 }
 
 function getRunningWorkflowIds() {
-  jq ".workflow_runs | .[] | select(.head_branch==\"${branch}\" and .head_repository.full_name==\"${repo}\" and .status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\") | .id " | grep -v "${GITHUB_RUN_ID}" || :
+  local workflow_ids=$(jq ".workflow_runs | .[] | select(.head_branch==\"${branch}\" and .head_repository.full_name==\"${repo}\" and .status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\") | .id ")
+  local condition="<"
+  for id in $workflow_ids; do
+    if [[ "$id" -gt "$GITHUB_RUN_ID" ]]; then
```
Comment (rokroskar) [inline entrypoint.sh:42]: would it be easier to move this to https://github.com/rokroskar/workflow-run-cleanup-action/blob/4e83cfafee097e787449c764fb6030c5dded55f9/entrypoint.sh#L68 and avoid having two if statements?

Comment (mustaphazorgati) [reply entrypoint.sh:42]: I can understand your idea. 
I have two reasons why I don't like it.
* logically the extraction of the id's should be done within `getRunningWorkflowIds`. An additional step to filter out newer workflows would add complexity somewhere where it logically doesn't belong.
* the extracted `workflow_ids` are typically not huge. When we assume that n=50 (which is very very big in my opinion.. why should anyone have 50 workflows running on the same branch) then the doubled execution time is still neglectable.

Personally I'd ignore the very minor extra computation in favor of clear structure and logical grouping. But it's your repo. If you want me to change it i'll do..

Comment (rokroskar) [reply entrypoint.sh:42]: sure that's fine with me if you prefer to keep it here

**Comment by rokroskar** [comment]
@mustaphazorgati thanks for this PR! Maybe we can fix up and merge #24 before this one?

**Comment by mustaphazorgati** [comment]
I will have some time later tonight. Around 22:00 CET. Then we can fix and merge all 3 open PRs if you have some time too.

**Comment by rokroskar** [comment]
Thanks so much @mustaphazorgati! 🎉

**Comment by mustaphazorgati** [comment]
Hey @rokroskar!
Sorry for the late reply. I was very exhausted and simply forgot. I've created #25. Please have alook. :) Maybe we can get all open PRs merged by the end of the weekend.

**Comment by rokroskar** [comment]
No problem at all, thanks for sending in the PR!

**Comment by mustaphazorgati** [comment]
@rokroskar, rebased :)

**Review by rokroskar — APPROVED** [review]
🚀
