### PR TITLE
fix: now considering head_repository for workflow cancelation 

### LINKED ISSUE #13: Pull Request cancels target branch with same name and vice verca
Hey there!

Currently (v0.3.0) this action behaves similar for pull requests and regular commits.
For pull requests the source branch of the pull request is regarded `BRANCH`.
For regular push events the branch of the repo is regarded `BRANCH`.
There is no other differentiation.

If a pull request source branch has the same name as a repo branch workflow runs on each of them will cancel each other out.

Expected behaviour: the pull request does not cancel the repo branch workflow, but other pull request (running) workflows. Same for the repo branch workflow.

### PR DESCRIPTION
**Pull request by mustaphazorgati**
Hey @rokroskar,

here is the promised PR. This PR now additionally differentiates between the head_repository.

Unfortunately the GitHub Actions [github context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) does not provide any information regarding the `head_repository`. 
That Information is extracted from the [GitHub Actions  API](https://docs.github.com/en/rest/reference/actions#get-a-workflow-run).

Furthermore I introduced 4 small functions to increase readability. I hope you like it.

closes #13

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -20,35 +15,47 @@ then
...
+function extractMetaInformation() {
+  jq "{ workflow_id: .workflow_id, branch: .head_branch, repo: .head_repository.full_name}"
+}
+
+function convertToKeyValuePairs() {
+  jq -r "to_entries | map(\"\(.key)=\(.value | tostring)\") | .[]"
+}
+
+function getRunningWorkflowIds() {
+  jq ".workflow_runs | .[] | select(.head_branch==\"${branch}\" and .head_repository.full_name==\"${repo}\" and .status==\"in_progress\" or .status==\"queued\" or .status== \"waiting\") | .id "
```
Comment (mustaphazorgati) [inline entrypoint.sh]: relying on the environment variables `branch` and `repo` is not optimal. We could pass those as function parameters, but then we have to document which parameter is what..
I've kept it this way because the script is very short and thus (for now) maintainable this way

File: entrypoint.sh [hunk 2]
```diff
@@ -20,35 +15,47 @@ then
...
+}
+
+function exportAll() {
+  for var in $1; do
+    export $var
+  done
+}
+
+# extract meta information for current workflow run
+exportAll "$(curl -s "${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" -H "${auth_header}" | extractMetaInformation | convertToKeyValuePairs)"
```
Comment (mustaphazorgati) [inline entrypoint.sh]: should we set the `"Accept: application/vnd.github.v3+json"` header here aswell? 
This [documentation](https://docs.github.com/en/rest/reference/actions#get-a-workflow-run) recommends that.

File: entrypoint.sh [hunk 3]
```diff
@@ -20,35 +15,47 @@ then
...
+echo "workflow id: $workflow_id"
+echo "branch: $branch"
+echo "repo: $repo"
 
-# get the run ids
-run_ids=$(curl -s ${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow_id}/runs -H "${auth_header}" | jq -r "${jq_run_ids}" | sort -n | head -n-1)
+# get the run ids for runs on same branch/repo
+run_ids=$(curl -s ${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow_id}/runs -H "${auth_header}" | getRunningWorkflowIds)
```
Comment (mustaphazorgati) [inline entrypoint.sh]: Same as above: 
should we set the "Accept: application/vnd.github.v3+json" header here aswell?
This [documentation](https://docs.github.com/en/rest/reference/actions#get-a-workflow) recommends that.

File: entrypoint.sh [hunk 4]
```diff
@@ -20,35 +15,47 @@ then
...
 
-echo "run ids: "$run_ids
+echo "run ids: ${run_ids}"
 
 # cancel the previous runs
-for run_id in $run_ids
-do
+for run_id in $run_ids; do
   curl -s -X POST -H "${auth_header}" ${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/cancel
```
Comment (mustaphazorgati) [inline entrypoint.sh]: Third time is the charm:
should we set the "Accept: application/vnd.github.v3+json" header here aswell?
This [documentation](https://docs.github.com/en/rest/reference/actions#cancel-a-workflow-run) recommends that.

File: entrypoint.sh (hunk 2 above)
Comment (rokroskar) [reply entrypoint.sh]: seems reasonable

File: entrypoint.sh (hunk 1 above)
Comment (rokroskar) [reply entrypoint.sh]: I agree it's not ideal - if it grows such a refactoring would definitely make sense

File: entrypoint.sh (hunk 2 above)
Comment (mustaphazorgati) [reply entrypoint.sh]: I didn't see your reaction in time.. fixed.

File: entrypoint.sh (hunk 3 above)
Comment (mustaphazorgati) [reply entrypoint.sh]: I didn't see your reaction in time.. fixed.

File: entrypoint.sh (hunk 4 above)
Comment (mustaphazorgati) [reply entrypoint.sh]: I didn't see your reaction in time.. fixed.

File: entrypoint.sh [hunk 5]
```diff
@@ -20,35 +15,48 @@ then
...
 
-echo "run ids: "$run_ids
+echo "run ids: ${run_ids}"
 
 # cancel the previous runs
-for run_id in $run_ids
-do
-  curl -s -X POST -H "${auth_header}" ${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/cancel
+for run_id in $run_ids; do
+  curl -s -X POST -H "${auth_header}" -H "${accept_header}" ${GITHUB_API}/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/cancel
```
Comment (rokroskar) [inline entrypoint.sh:60]: You need to make sure here that `run_id != $GITHUB_RUN_ID` - atm this script cancels itself out

**Review by rokroskar — CHANGES_REQUESTED** [review]
Looks like a nice improvement, thanks @musaphazorgati! Please make sure that the script doesn't cancel the run that it is itself a part of - otherwise looks good.

File: entrypoint.sh (hunk 5 above)
Comment (mustaphazorgati) [reply entrypoint.sh:60]: Good catch. Update coming asap

Comment (mustaphazorgati) [reply entrypoint.sh:60]: done in `getRunningWorkflowIds`

**Comment by mustaphazorgati** [comment]
> Looks like a nice improvement, thanks @musaphazorgati! Please make sure that the script doesn't cancel the run that it is itself a part of - otherwise looks good.

you're welcome :blush: 
Fix is pushed ;)

**Review by rokroskar — APPROVED** [review]
Seems to work as advertised! thanks!
